import React from "react";
import { Box, Button, Heading, Image, Text } from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";
const MovieDetails = ({ data }) => {
  const handleAddWishlist = async () => {
    try {
      const res = await axios.post(`http://localhost:8080/wishlists`, data);
      alert(`Added to Wishlist`);
    } catch (error) {
      alert(`Already Exist or Network Error`);
      console.log(error);
    }
  };
  return (
    <>
      <Head>
        <title>Movies Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display="flex" justifyContent="space-between" width="85%" m="auto">
        <Box mt="40px">
          <Image
            minH="320px"
            src={data.Images[2]}
            alt="img"
            width="100%"
          ></Image>
        </Box>
        <Box p="20px">
          <Text fontSize="40px" fontWeight="bold" mt="5px">
            {data.Title}
          </Text>
          <Text fontSize="20px" fontWeight="bold">
            Rating:{" "}
            <span style={{ fontSize: "20px", fontWeight: "normal" }}>
              {data.imdbRating}
            </span>
          </Text>
          <Text fontSize="20px" fontWeight="bold">
            Released:{" "}
            <span style={{ fontSize: "20px", fontWeight: "normal" }}>
              {data.Released} {data.Language}
            </span>
          </Text>
          <Text fontSize="20px" fontWeight="bold">
            Genre:{" "}
            <span style={{ fontSize: "20px", fontWeight: "normal" }}>
              {data.Genre}
            </span>
          </Text>
          <Text fontSize="20px" fontWeight="bold">
            Description:{" "}
            <span style={{ fontSize: "20px", fontWeight: "normal" }}>
              {data.Plot}
            </span>
          </Text>
          <Text fontSize="20px" fontWeight="bold">
            Awards:{" "}
            <span style={{ fontSize: "20px", fontWeight: "normal" }}>
              {data.Awards}
            </span>
          </Text>
          <Text fontSize="20px" fontWeight="bold">
            Actors:{" "}
            <span style={{ fontSize: "20px", fontWeight: "normal" }}>
              {data.Actors}
            </span>
          </Text>
          <Button
            w="100%"
            mt="20px"
            padding="15px"
            colorScheme="blue"
            onClick={handleAddWishlist}
          >
            ADD TO WISHLIST
          </Button>
        </Box>
      </Box>
    </>
  );
};

export default MovieDetails;

export async function getStaticPaths() {
  const res = await axios.get(`https://movies-database-gold.vercel.app/movies`);
  const data = await res.data;
  return {
    paths: data.map((el) => ({
      params: {
        id: el.id.toString(),
      },
    })),
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const {
    params: { id },
  } = context;
  const res = await axios.get(
    `https://movies-database-gold.vercel.app/movies/${id}`
  );
  const data = await res.data;
  return {
    props: { data },
  };
}
