import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Box, Button, Heading, Image, Text } from "@chakra-ui/react";
import axios from "axios";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  const handleAddWishlist = async (movie) => {
    try {
      const res = await axios.post(`http://localhost:8080/wishlists`, movie);
      alert("Added to Wishlist");
    } catch (error) {
      alert(`Already Exist or Network Error`);
      console.log(error);
    }
  };
  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading textAlign="center">Movie Lists</Heading>
      <Box
        display="grid"
        gridTemplateColumns="repeat(3,1fr)"
        width="80%"
        m="auto"
        gap="20px"
      >
        {data.map((el) => (
          <Box border="1px solid" key={el.id}>
            <Link href={`wishlist/${el.id}`}>
              <Image
                width="100%"
                maxH="200px"
                src={el.Images[1]}
                alt="ApiImg"
              ></Image>
            </Link>
            <Box p="10px">
              <Text fontSize="20px" fontWeight="bold" mb="5px">
                {el.Title} ({el.Year})
              </Text>
              <Text mb="5px">{el.Language}</Text>
              <Button
                colorScheme="blue"
                onClick={() => {
                  handleAddWishlist(el);
                }}
              >
                ADD TO WISHLIST
              </Button>
            </Box>
          </Box>
        ))}
      </Box>
    </>
  );
}

export async function getStaticProps() {
  const res = await axios.get(`https://movies-database-gold.vercel.app/movies`);
  const data = await res.data;
  return {
    props: { data },
  };
}
